package com.gamemaker.ExtensionCore.ExtBridge;
import java.lang.String;
import java.nio.ByteBuffer;
import ${YYAndroidPackageName}.GMExtUtils;

public final class GMDiscordSocialBridge {
    static {
        // this is the extension lib name
        System.loadLibrary("GMDiscordSocial");
        nativeRegister();
    }
    // this registers the native functions on the C++ layer
    private static native void nativeRegister();

    public static String __EXT_JAVA__GetExtensionOption(String extName, String optName)
    {
        return GMExtUtils.GetExtensionOption(extName, optName);
    }

    public static native double __EXT_JNI__GMDiscordSocial_invocation_handler(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__GMDiscordSocial_queue_buffer(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_run_callbacks();
    public static native double __EXT_JNI__discord_social_init(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_shutdown();
    public static native double __EXT_JNI__discord_social_client_end_call(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_end_calls(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_call(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_calls(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_current_input_device(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_current_output_device(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_input_devices(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_input_volume();
    public static native double __EXT_JNI__discord_social_client_get_output_devices(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_output_volume();
    public static native double __EXT_JNI__discord_social_client_get_self_deaf_all();
    public static native double __EXT_JNI__discord_social_client_get_self_mute_all();
    public static native double __EXT_JNI__discord_social_client_set_automatic_gain_control(double on);
    public static native double __EXT_JNI__discord_social_client_set_device_change_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_echo_cancellation(double on);
    public static native double __EXT_JNI__discord_social_client_set_input_device(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_input_volume(double vol);
    public static native double __EXT_JNI__discord_social_client_set_no_audio_input_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_no_audio_input_threshold(double threshold);
    public static native double __EXT_JNI__discord_social_client_set_noise_suppression(double on);
    public static native double __EXT_JNI__discord_social_client_set_opus_hardware_coding(double encode, double decode);
    public static native double __EXT_JNI__discord_social_client_set_output_device(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_output_volume(double vol);
    public static native double __EXT_JNI__discord_social_client_set_self_deaf_all(double deaf);
    public static native double __EXT_JNI__discord_social_client_set_self_mute_all(double mute);
    public static native double __EXT_JNI__discord_social_client_set_thread_priority(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_voice_participant_changed_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_show_audio_route_picker();
    public static native double __EXT_JNI__discord_social_client_start_call(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__discord_social_call_audio_should_mute(double should_mute);
    public static native double __EXT_JNI__discord_social_client_start_call_with_audio_callbacks(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__discord_social_call_fetch_received_data(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__discord_social_call_fetch_captured_data(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__discord_social_client_abort_authorize();
    public static native double __EXT_JNI__discord_social_client_abort_get_token_from_device();
    public static native String __EXT_JNI__discord_social_client_create_authorization_code_verifier();
    public static native double __EXT_JNI__discord_social_client_authorize(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_close_authorize_device_screen();
    public static native double __EXT_JNI__discord_social_client_get_provisional_token(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_token(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_token_from_device(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_token_from_device_provisional_merge(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_token_from_provisional_merge(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_is_authenticated();
    public static native double __EXT_JNI__discord_social_client_open_authorize_device_screen(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_provisional_user_merge_completed(double success);
    public static native double __EXT_JNI__discord_social_client_refresh_token(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_authorize_device_screen_closed_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_game_window_pid(double pid);
    public static native double __EXT_JNI__discord_social_client_set_token_expiration_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_update_provisional_account_display_name(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_update_token(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_revoke_token(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_exchange_child_token(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_unmerge_into_provisional_account(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_register_authorize_request_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_can_open_message_in_discord(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_delete_user_message(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_channel_handle(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_message_handle(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__discord_social_client_open_message_in_discord(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_send_lobby_message(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_send_lobby_message_with_metadata(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_send_user_message(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_send_user_message_with_metadata(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_message_created_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_message_deleted_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_message_updated_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_showing_chat(double showing_chat);
    public static native double __EXT_JNI__discord_social_client_edit_user_message(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_lobby_messages_with_limit(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_user_message_summaries(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_user_messages_with_limit(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_add_log_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_add_voice_log_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_connect();
    public static native double __EXT_JNI__discord_social_client_disconnect();
    public static native double __EXT_JNI__discord_social_client_get_status(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_log_dir(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_status_changed_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_voice_log_dir(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_create_or_join_lobby(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_create_or_join_lobby_with_metadata(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_guild_channels(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_lobby_handle(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_lobby_ids(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_user_guilds(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_leave_lobby(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_link_channel_to_lobby(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_lobby_created_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_lobby_deleted_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_lobby_member_added_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_lobby_member_removed_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_lobby_member_updated_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_lobby_updated_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_unlink_channel_from_lobby(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_join_linked_lobby_guild(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_accept_activity_invite(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_clear_rich_presence();
    public static native double __EXT_JNI__discord_social_client_register_launch_command(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_register_launch_steam_application(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_send_activity_invite(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_send_activity_join_request(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_send_activity_join_request_reply(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_activity_invite_created_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_activity_invite_updated_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_activity_join_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_activity_join_with_application_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_online_status(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_update_rich_presence(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_accept_discord_friend_request(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_accept_game_friend_request(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_block_user(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_cancel_discord_friend_request(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_cancel_game_friend_request(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_relationship_handle(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_relationships(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_relationships_by_group(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__discord_social_client_reject_discord_friend_request(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_reject_game_friend_request(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_remove_discord_and_game_friend(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_remove_game_friend(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_search_friends_by_username(String search_str, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__discord_social_client_send_discord_friend_request(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_send_discord_friend_request_by_id(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_send_game_friend_request(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_send_game_friend_request_by_id(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_relationship_created_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_relationship_deleted_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_relationship_groups_updated_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_unblock_user(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_current_user(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_discord_client_connected_user(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_get_user(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_user_updated_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native String __EXT_JNI__discord_social_client_error_to_string(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native String __EXT_JNI__discord_social_client_get_default_audio_device_id();
    public static native String __EXT_JNI__discord_social_client_get_default_communication_scopes();
    public static native String __EXT_JNI__discord_social_client_get_default_presence_scopes();
    public static native String __EXT_JNI__discord_social_client_get_version_hash();
    public static native double __EXT_JNI__discord_social_client_get_version_major();
    public static native double __EXT_JNI__discord_social_client_get_version_minor();
    public static native double __EXT_JNI__discord_social_client_get_version_patch();
    public static native double __EXT_JNI__discord_social_client_get_application_id(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__discord_social_client_set_application_id(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_is_discord_app_installed(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_open_connected_games_settings_in_discord(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native String __EXT_JNI__discord_social_client_status_to_string(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native String __EXT_JNI__discord_social_client_thread_to_string(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_call_get_local_mute(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_call_get_participant_volume(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_call_get_ptt_release_delay(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_call_get_vad_threshold(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__discord_social_call_get_voice_state_handle(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__discord_social_call_set_audio_mode(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_call_set_local_mute(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_call_set_on_voice_state_changed_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_call_set_participant_changed_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_call_set_participant_volume(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_call_set_ptt_active(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_call_set_ptt_release_delay(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_call_set_self_deaf(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_call_set_self_mute(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_call_set_speaking_status_changed_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_call_set_status_changed_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_call_set_vad_threshold(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_client_remove_device_change_callback();
    public static native double __EXT_JNI__discord_social_client_remove_no_audio_input_callback();
    public static native double __EXT_JNI__discord_social_client_remove_voice_participant_changed_callback();
    public static native double __EXT_JNI__discord_social_client_remove_authorize_device_screen_closed_callback();
    public static native double __EXT_JNI__discord_social_client_remove_token_expiration_callback();
    public static native double __EXT_JNI__discord_social_client_remove_message_created_callback();
    public static native double __EXT_JNI__discord_social_client_remove_message_deleted_callback();
    public static native double __EXT_JNI__discord_social_client_remove_message_updated_callback();
    public static native double __EXT_JNI__discord_social_client_remove_log_callback();
    public static native double __EXT_JNI__discord_social_client_remove_status_changed_callback();
    public static native double __EXT_JNI__discord_social_client_remove_lobby_created_callback();
    public static native double __EXT_JNI__discord_social_client_remove_lobby_deleted_callback();
    public static native double __EXT_JNI__discord_social_client_remove_lobby_member_added_callback();
    public static native double __EXT_JNI__discord_social_client_remove_lobby_member_removed_callback();
    public static native double __EXT_JNI__discord_social_client_remove_lobby_member_updated_callback();
    public static native double __EXT_JNI__discord_social_client_remove_lobby_updated_callback();
    public static native double __EXT_JNI__discord_social_client_remove_activity_invite_created_callback();
    public static native double __EXT_JNI__discord_social_client_remove_activity_invite_updated_callback();
    public static native double __EXT_JNI__discord_social_client_remove_activity_join_callback();
    public static native double __EXT_JNI__discord_social_client_remove_activity_join_with_application_callback();
    public static native double __EXT_JNI__discord_social_client_remove_authorize_request_callback();
    public static native double __EXT_JNI__discord_social_client_remove_relationship_created_callback();
    public static native double __EXT_JNI__discord_social_client_remove_relationship_deleted_callback();
    public static native double __EXT_JNI__discord_social_client_remove_relationship_groups_updated_callback();
    public static native double __EXT_JNI__discord_social_client_remove_user_updated_callback();
    public static native double __EXT_JNI__discord_social_call_remove_on_voice_state_changed_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_call_remove_participant_changed_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_call_remove_speaking_status_changed_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__discord_social_call_remove_status_changed_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
}